#include "civic/cadastre/CadastreMutation.hpp"
#include <algorithm>
#include <cmath>
#include <map>

namespace civic::cadastre {
namespace {
using civic::geometry::Point; using civic::geometry::Polygon; using civic::geometry::Segment;
bool same(Point a,Point b){return a==b;}
long double parameter(Point p,Point a,Point b){const auto dx=b.x-a.x,dy=b.y-a.y;const long double denom=static_cast<long double>(dx)*dx+static_cast<long double>(dy)*dy;if(denom==0)return 0;return (static_cast<long double>(p.x-a.x)*dx+static_cast<long double>(p.y-a.y)*dy)/denom;}
bool chord_inside(const Polygon& polygon,Segment chord){for(int step=1;step<32;++step){const long double t=static_cast<long double>(step)/32.0L;Point p{static_cast<civic::geometry::Coordinate>(std::llround(chord.a.x+(chord.b.x-chord.a.x)*t)),static_cast<civic::geometry::Coordinate>(std::llround(chord.a.y+(chord.b.y-chord.a.y)*t))};if(!civic::geometry::point_in_polygon(p,polygon))return false;}return true;}
civic::core::Result<std::pair<Polygon,Polygon>> split_by_chord(const Polygon& input,Segment chord) noexcept {try{auto canonical=civic::geometry::canonicalize(input);if(!canonical)return std::unexpected(canonical.error());if(same(chord.a,chord.b)||!chord_inside(*canonical,chord))return std::unexpected(civic::core::error(civic::core::ErrorCode::invalid_argument,"split chord must cross parcel interior"));std::vector<Point> expanded;expanded.reserve(canonical->vertices.size()+2);bool found_a=false,found_b=false;for(std::size_t i=0;i<canonical->vertices.size();++i){const auto start=canonical->vertices[i],end=canonical->vertices[(i+1)%canonical->vertices.size()];expanded.push_back(start);std::vector<Point> insert;for(const auto p:{chord.a,chord.b}){if(civic::geometry::point_on_segment(p,{start,end})){if(same(p,start)){if(same(p,chord.a))found_a=true;else found_b=true;}else if(!same(p,end))insert.push_back(p);}}std::sort(insert.begin(),insert.end(),[&](Point l,Point r){return parameter(l,start,end)<parameter(r,start,end);});for(const auto p:insert){if(expanded.back()!=p)expanded.push_back(p);if(same(p,chord.a))found_a=true;else if(same(p,chord.b))found_b=true;}}for(const auto p:expanded){if(same(p,chord.a))found_a=true;if(same(p,chord.b))found_b=true;}if(!found_a||!found_b)return std::unexpected(civic::core::error(civic::core::ErrorCode::invalid_argument,"split endpoints must lie on parcel boundary"));auto ia=std::find(expanded.begin(),expanded.end(),chord.a),ib=std::find(expanded.begin(),expanded.end(),chord.b);if(ia==expanded.end()||ib==expanded.end())return std::unexpected(civic::core::error(civic::core::ErrorCode::invalid_argument,"split endpoints were not inserted"));const auto aidx=static_cast<std::size_t>(ia-expanded.begin()),bidx=static_cast<std::size_t>(ib-expanded.begin());auto collect=[&](std::size_t from,std::size_t to){Polygon out;for(std::size_t i=from;;i=(i+1)%expanded.size()){out.vertices.push_back(expanded[i]);if(i==to)break;}return civic::geometry::canonicalize(out);};auto left=collect(aidx,bidx),right=collect(bidx,aidx);if(!left)return std::unexpected(left.error());if(!right)return std::unexpected(right.error());if(civic::geometry::area_square_meters(*left)<1.0||civic::geometry::area_square_meters(*right)<1.0)return std::unexpected(civic::core::error(civic::core::ErrorCode::invalid_argument,"split produces sub-minimum parcel"));return std::pair<Polygon,Polygon>{std::move(*left),std::move(*right)};}catch(const std::exception&e){return std::unexpected(civic::core::error(civic::core::ErrorCode::internal_error,e.what()));}}
Parcel child_from(const Parcel& source,std::string external,Polygon boundary,std::vector<civic::core::ParcelId> parents){Parcel child=source;child.id=parcel_id_from_external(external);child.external_id=std::move(external);child.boundary=std::move(boundary);child.historical_parent_ids=canonical_ids(std::move(parents));child.boundaries.clear();child.frontage_boundary_ids.clear();child.access_boundary_ids.clear();child.live=true;return child;}
std::vector<civic::core::ParcelId> inherited_parents(std::span<const Parcel* const> parcels){std::vector<civic::core::ParcelId> ids;for(const auto* parcel:parcels){ids.push_back(parcel->id);ids.insert(ids.end(),parcel->historical_parent_ids.begin(),parcel->historical_parent_ids.end());}return canonical_ids(std::move(ids));}
std::string lineage_id(std::uint64_t tick,std::string_view kind){return "lineage:"+std::to_string(tick)+":"+std::string{kind};}
}
std::uint64_t CadastralMutationService::next_sequence() const noexcept {return graph_.lineage().size()+1;}
std::uint64_t CadastralMutationService::next_lineage_tick() const noexcept {std::uint64_t tick=0;for(const auto&e:graph_.lineage())tick=std::max(tick,e.tick);return tick+1;}
civic::core::Result<void> CadastralMutationService::validate_dependents(const CadastralGraph& staged) const noexcept {try{for(const auto& validator:validators_){auto result=validator(staged);if(!result)return result;}return {};}catch(const std::exception&e){return std::unexpected(civic::core::error(civic::core::ErrorCode::internal_error,e.what()));}catch(...){return std::unexpected(civic::core::error(civic::core::ErrorCode::internal_error,"dependent cadastral validation failed"));}}

civic::core::Result<MutationResult> CadastralMutationService::split(const ParcelSplitCommand& command) noexcept {const auto* source=graph_.find(command.parcel_id);if(!source||!source->live)return std::unexpected(civic::core::error(civic::core::ErrorCode::not_found,"live source parcel not found"));auto pieces=split_by_chord(source->boundary,command.cut);if(!pieces)return std::unexpected(pieces.error());CadastreTransaction transaction{graph_};auto& staged=transaction.staged();const auto sequence=next_sequence();const auto left_external="parcel:"+source->external_id+":split:"+std::to_string(sequence)+":0";const auto right_external="parcel:"+source->external_id+":split:"+std::to_string(sequence)+":1";std::vector<const Parcel*> parents{source};auto historical=inherited_parents(parents);auto left=child_from(*source,left_external,std::move(pieces->first),historical);auto right=child_from(*source,right_external,std::move(pieces->second),historical);const auto source_id=source->id,left_id=left.id,right_id=right.id;if(auto r=staged.retire(source_id);!r)return std::unexpected(r.error());if(auto r=staged.insert(std::move(left));!r)return std::unexpected(r.error());if(auto r=staged.insert(std::move(right));!r)return std::unexpected(r.error());for(const auto&[_,e]:staged.easements())if(std::find(e.parcel_ids.begin(),e.parcel_ids.end(),source_id)!=e.parcel_ids.end())return std::unexpected(civic::core::error(civic::core::ErrorCode::conflict,"split parcel has easement; explicit easement rewrite required"));const auto tick=next_lineage_tick();if(auto r=staged.append_lineage({lineage_id(tick,"split"),tick,"split",{source_id},{left_id,right_id}});!r)return std::unexpected(r.error());if(auto r=validate_dependents(staged);!r)return std::unexpected(r.error());if(auto r=transaction.commit();!r)return std::unexpected(r.error());return MutationResult{{source_id},{left_id,right_id},graph_.revision()};}

civic::core::Result<MutationResult> CadastralMutationService::assemble(const ParcelAssemblyCommand& command) noexcept {auto ids=canonical_ids(command.parcel_ids);if(ids.size()<2)return std::unexpected(civic::core::error(civic::core::ErrorCode::invalid_argument,"assembly requires at least two parcels"));std::vector<const Parcel*> sources;std::vector<Polygon> polygons;for(const auto id:ids){const auto* p=graph_.find(id);if(!p||!p->live)return std::unexpected(civic::core::error(civic::core::ErrorCode::not_found,"assembly source parcel not found"));sources.push_back(p);polygons.push_back(p->boundary);}const auto* first=sources.front();for(const auto* p:sources)if(p->block_id!=first->block_id||p->zoning_district_id!=first->zoning_district_id||p->owner_id!=first->owner_id)return std::unexpected(civic::core::error(civic::core::ErrorCode::conflict,"assembly parcels must share block zoning and owner"));for(const auto&[_,e]:graph_.easements())for(const auto id:ids)if(std::find(e.parcel_ids.begin(),e.parcel_ids.end(),id)!=e.parcel_ids.end())return std::unexpected(civic::core::error(civic::core::ErrorCode::conflict,"assembly parcel has easement"));auto united=civic::geometry::polygon_union(polygons);if(!united)return std::unexpected(united.error());if(united->size()!=1)return std::unexpected(civic::core::error(civic::core::ErrorCode::invalid_argument,"assembly parcels are disconnected"));std::string external="parcel:assembly:"+std::to_string(next_sequence());for(const auto* p:sources)external+=":"+p->external_id;auto assembled=child_from(*first,external,std::move(united->front()),inherited_parents(sources));CadastreTransaction transaction{graph_};auto& staged=transaction.staged();for(const auto id:ids)if(auto r=staged.retire(id);!r)return std::unexpected(r.error());const auto result_id=assembled.id;if(auto r=staged.insert(std::move(assembled));!r)return std::unexpected(r.error());const auto tick=next_lineage_tick();if(auto r=staged.append_lineage({lineage_id(tick,"assembly"),tick,"assembly",ids,{result_id}});!r)return std::unexpected(r.error());if(auto r=validate_dependents(staged);!r)return std::unexpected(r.error());if(auto r=transaction.commit();!r)return std::unexpected(r.error());return MutationResult{ids,{result_id},graph_.revision()};}

civic::core::Result<void> CadastralMutationService::create_easement(const EasementCreateCommand& command) noexcept {CadastreTransaction transaction{graph_};auto& staged=transaction.staged();for(const auto id:command.parcel_ids){const auto* parcel=staged.find(id);if(!parcel||!parcel->live)return std::unexpected(civic::core::error(civic::core::ErrorCode::not_found,"easement parcel not found"));for(const auto point:command.geometry)if(!civic::geometry::point_in_polygon(point,parcel->boundary))return std::unexpected(civic::core::error(civic::core::ErrorCode::invalid_argument,"easement geometry must remain inside referenced parcels"));}if(auto r=staged.add_easement({command.id,command.parcel_ids,command.kind,command.geometry});!r)return std::unexpected(r.error());if(auto r=validate_dependents(staged);!r)return r;return transaction.commit();}
civic::core::Result<void> CadastralMutationService::remove_easement(std::string_view id) noexcept {CadastreTransaction transaction{graph_};auto& staged=transaction.staged();auto r=staged.remove_easement(id);if(!r)return r;if(auto check=validate_dependents(staged);!check)return check;return transaction.commit();}

civic::core::Result<MutationResult> CadastralMutationService::dedicate_right_of_way(const RightOfWayCommand& command) noexcept {const auto* source=graph_.find(command.parcel_id);if(!source||!source->live)return std::unexpected(civic::core::error(civic::core::ErrorCode::not_found,"ROW source parcel not found"));for(const auto point:command.dedicated_area.vertices)if(!civic::geometry::point_in_polygon(point,source->boundary))return std::unexpected(civic::core::error(civic::core::ErrorCode::invalid_argument,"ROW dedication must be contained by parcel"));auto residual=civic::geometry::polygon_difference(source->boundary,command.dedicated_area);if(!residual)return std::unexpected(residual.error());if(residual->size()!=1||civic::geometry::area_square_meters(residual->front())<1.0)return std::unexpected(civic::core::error(civic::core::ErrorCode::invalid_argument,"ROW dedication must leave one viable residual parcel"));const auto external="parcel:"+source->external_id+":row:"+std::to_string(next_sequence());std::vector<const Parcel*> source_span{source};auto result=child_from(*source,external,std::move(residual->front()),inherited_parents(source_span));CadastreTransaction transaction{graph_};auto& staged=transaction.staged();const auto old_id=source->id,new_id=result.id;if(auto r=staged.retire(old_id);!r)return std::unexpected(r.error());if(auto r=staged.insert(std::move(result));!r)return std::unexpected(r.error());const auto tick=next_lineage_tick();if(auto r=staged.append_lineage({lineage_id(tick,"right-of-way"),tick,"right-of-way",{old_id},{new_id}});!r)return std::unexpected(r.error());if(auto r=validate_dependents(staged);!r)return std::unexpected(r.error());if(auto r=transaction.commit();!r)return std::unexpected(r.error());return MutationResult{{old_id},{new_id},graph_.revision()};}
}
