#include "civic/world/Hydrology.hpp"
#include <algorithm>
#include <array>
#include <cmath>
#include <iomanip>
#include <limits>
#include <queue>
#include <sstream>

namespace civic::world {
namespace {
constexpr std::array<std::pair<int,int>,8> d8{{{0,-1},{1,-1},{1,0},{1,1},{0,1},{-1,1},{-1,0},{-1,-1}}};
bool valid_dims(std::uint32_t w,std::uint32_t h,std::size_t n){return w>0&&h>0&&n==static_cast<std::size_t>(w)*h;}
bool boundary(std::uint32_t i,std::uint32_t w,std::uint32_t h){auto x=i%w,y=i/w;return x==0||y==0||x==w-1||y==h-1;}
std::vector<std::pair<std::uint32_t,int>> neighbors(std::uint32_t i,std::uint32_t w,std::uint32_t h){std::vector<std::pair<std::uint32_t,int>> out;int x=static_cast<int>(i%w),y=static_cast<int>(i/w);for(int o=0;o<8;++o){auto [dx,dy]=d8[o];int nx=x+dx,ny=y+dy;if(nx>=0&&ny>=0&&nx<static_cast<int>(w)&&ny<static_cast<int>(h))out.emplace_back(static_cast<std::uint32_t>(ny)*w+static_cast<std::uint32_t>(nx),o);}return out;}
std::string ordinal(std::uint32_t value,int width){std::ostringstream s;s<<std::setw(width)<<std::setfill('0')<<value;return s.str();}
}
civic::core::Result<std::vector<double>> resolve_depressions(std::uint32_t w,std::uint32_t h,const std::vector<double>& raw,const std::vector<std::uint8_t>& water) noexcept {
  if(!valid_dims(w,h,raw.size())||water.size()!=raw.size())return std::unexpected(civic::core::error(civic::core::ErrorCode::invalid_argument,"invalid hydrology dimensions"));
  for(double v:raw)if(!std::isfinite(v))return std::unexpected(civic::core::error(civic::core::ErrorCode::invalid_argument,"elevation must be finite"));
  struct Entry{double e;std::uint32_t i;};struct Greater{bool operator()(const Entry&a,const Entry&b)const{return a.e>b.e||(a.e==b.e&&a.i>b.i);}};std::priority_queue<Entry,std::vector<Entry>,Greater> heap;std::vector<double> c=raw;std::vector<std::uint8_t> visited(raw.size());auto seed=[&](std::uint32_t i){if(visited[i])return;visited[i]=1;heap.push({c[i],i});};
  for(std::uint32_t i=0;i<raw.size();++i)if(boundary(i,w,h)||water[i])seed(i);
  while(!heap.empty()){auto cur=heap.top();heap.pop();for(auto [n,_]:neighbors(cur.i,w,h)){if(visited[n])continue;visited[n]=1;c[n]=std::max(raw[n],cur.e);heap.push({c[n],n});}}return c;
}
civic::core::Result<HydrologyState> build_hydrology(const TerrainField& terrain,const std::vector<double>& conditioned) noexcept {
  const auto w=terrain.width,h=terrain.height,count=static_cast<std::uint32_t>(conditioned.size());if(!valid_dims(w,h,conditioned.size())||terrain.samples.size()!=conditioned.size())return std::unexpected(civic::core::error(civic::core::ErrorCode::invalid_argument,"hydrology dimensions do not match terrain"));
  std::vector<std::uint8_t> water(count);for(std::uint32_t i=0;i<count;++i)water[i]=terrain.samples[i].surface_water==SurfaceWaterClass::none?0:1;
  std::vector<std::optional<std::uint32_t>> recv(count);std::vector<int> lower(count,-1),rank(count,-1);std::vector<std::uint8_t> outlet(count);std::vector<std::uint32_t> q;
  for(std::uint32_t i=0;i<count;++i){if(boundary(i,w,h)||water[i]){outlet[i]=1;rank[i]=0;q.push_back(i);continue;}int best=-1;double bestg=-std::numeric_limits<double>::infinity();for(auto[n,o]:neighbors(i,w,h)){double drop=conditioned[i]-conditioned[n];if(drop<=hydrology_epsilon)continue;double g=drop/((o%2)?std::sqrt(2.0):1.0);if(g>bestg+hydrology_epsilon){bestg=g;best=static_cast<int>(n);}}if(best>=0){lower[i]=best;recv[i]=static_cast<std::uint32_t>(best);rank[i]=0;q.push_back(i);}}
  std::sort(q.begin(),q.end());for(std::size_t head=0;head<q.size();++head){auto cur=q[head];for(auto[n,_]:neighbors(cur,w,h)){if(rank[n]!=-1||std::abs(conditioned[n]-conditioned[cur])>hydrology_epsilon)continue;rank[n]=rank[cur]+1;q.push_back(n);}}
  for(std::uint32_t i=0;i<count;++i){if(outlet[i]||lower[i]>=0)continue;int chosen=-1;if(rank[i]>0)for(auto[n,_]:neighbors(i,w,h))if(std::abs(conditioned[n]-conditioned[i])<=hydrology_epsilon&&rank[n]==rank[i]-1){chosen=static_cast<int>(n);break;}if(chosen<0)return std::unexpected(civic::core::error(civic::core::ErrorCode::invariant_failure,"conditioned terrain contains undrained flat"));recv[i]=static_cast<std::uint32_t>(chosen);}
  std::vector<int> indegree(count);for(auto t:recv)if(t)++indegree[*t];std::vector<std::uint32_t> zero;for(std::uint32_t i=0;i<count;++i)if(indegree[i]==0)zero.push_back(i);std::sort(zero.begin(),zero.end());std::vector<std::uint32_t> order;while(!zero.empty()){auto cur=zero.front();zero.erase(zero.begin());order.push_back(cur);if(recv[cur]){auto t=*recv[cur];if(--indegree[t]==0){auto it=std::upper_bound(zero.begin(),zero.end(),t);zero.insert(it,t);}}}if(order.size()!=count)return std::unexpected(civic::core::error(civic::core::ErrorCode::invariant_failure,"drainage cycle"));
  std::vector<double> accum(count,1);for(auto i:order)if(recv[i])accum[*recv[i]]+=accum[i];std::vector<int> outlet_by(count,-1);auto resolve=[&](std::uint32_t start){std::vector<std::uint32_t> path;auto cur=start;while(outlet_by[cur]<0){path.push_back(cur);if(!recv[cur]){outlet_by[cur]=static_cast<int>(cur);break;}cur=*recv[cur];}int o=outlet_by[cur];for(auto p:path)outlet_by[p]=o;return o;};std::vector<int> outlets;for(std::uint32_t i=0;i<count;++i){int o=resolve(i);if(std::find(outlets.begin(),outlets.end(),o)==outlets.end())outlets.push_back(o);}std::sort(outlets.begin(),outlets.end());
  std::vector<std::string> ids(count);for(std::uint32_t i=0;i<count;++i){auto pos=std::lower_bound(outlets.begin(),outlets.end(),outlet_by[i])-outlets.begin();ids[i]="watershed:"+ordinal(static_cast<std::uint32_t>(pos),4);}const auto threshold=std::max<std::uint32_t>(12,static_cast<std::uint32_t>(std::floor(count*.015)));const double cell_area=terrain.meters_per_cell*terrain.meters_per_cell;std::vector<ChannelSegment> channels;for(std::uint32_t i=0;i<count;++i)if(recv[i]&&accum[i]>=threshold)channels.push_back({"channel:"+ordinal(i,6),i,*recv[i],accum[i],std::round(cell_area*.02*std::sqrt(accum[i])*1e6)/1e6});
  std::vector<WatershedRecord> watersheds;for(std::size_t oi=0;oi<outlets.size();++oi){const auto id="watershed:"+ordinal(static_cast<std::uint32_t>(oi),4);std::uint32_t members=0;for(const auto& x:ids)if(x==id)++members;std::optional<std::string> primary;double best=-1;for(const auto& c:channels)if(ids[c.from_index]==id&&(c.accumulation>best||(c.accumulation==best&&(!primary||c.id<*primary)))){best=c.accumulation;primary=c.id;}watersheds.push_back({id,static_cast<std::uint32_t>(outlets[oi]),members,accum[outlets[oi]],primary});}
  double min=*std::min_element(conditioned.begin(),conditioned.end()),max=*std::max_element(conditioned.begin(),conditioned.end()),range=std::max(1e-9,max-min),maxacc=*std::max_element(accum.begin(),accum.end());std::vector<double> sus(count);for(std::uint32_t i=0;i<count;++i){double af=std::log1p(accum[i])/std::log1p(std::max(1.0,maxacc)),low=1-(conditioned[i]-min)/range;int x=static_cast<int>(i%w),y=static_cast<int>(i/w),best=999;for(const auto& c:channels)for(auto t:{c.from_index,c.to_index})best=std::min(best,std::max(std::abs(x-static_cast<int>(t%w)),std::abs(y-static_cast<int>(t/w))));double cf=best==0?1:best==1?.65:best==2?.3:0;double val=std::clamp(af*.52+low*.30+cf*.18,0.0,1.0);sus[i]=std::round(val*1e6)/1e6;}
  return HydrologyState{w,h,conditioned,recv,watersheds,channels,accum,ids,sus};
}
civic::core::Result<FloodResult> run_design_storm(const DesignStormEvent& e,const TerrainField& t,const HydrologyState& h,const std::vector<double>* impervious) noexcept {
  if(e.id.empty()||!std::isfinite(e.rainfall_mm)||e.rainfall_mm<0||!std::isfinite(e.duration_hours)||e.duration_hours<0||!std::isfinite(e.saturation_factor)||e.saturation_factor<0||e.saturation_factor>1)return std::unexpected(civic::core::error(civic::core::ErrorCode::invalid_argument,"invalid storm event"));
  const std::size_t count=static_cast<std::size_t>(t.width)*t.height;if(h.receiver.size()!=count||t.samples.size()!=count||(impervious&&impervious->size()!=count))return std::unexpected(civic::core::error(civic::core::ErrorCode::invalid_argument,"flood dimensions mismatch"));double area=t.meters_per_cell*t.meters_per_cell,rpc=e.rainfall_mm/1000*area,rain=rpc*static_cast<double>(count);if(rain==0)return FloodResult{e.id,std::vector<double>(count),0,0,0,0,0,0};std::vector<double> incoming(count),runoff(count),depth(count);double infiltration=0;for(std::size_t i=0;i<count;++i){double imp=impervious?std::clamp((*impervious)[i],0.0,1.0):0;double cap=soil_properties(t.samples[i].soil_class).infiltration_mm_per_hour*e.duration_hours*e.saturation_factor*(1-imp),mm=std::min(e.rainfall_mm,std::max(0.0,cap)),iv=mm/1000*area;infiltration+=iv;runoff[i]=std::max(0.0,rpc-iv);}std::vector<int> indegree(count);for(auto r:h.receiver)if(r)++indegree[*r];std::vector<std::uint32_t> zero;for(std::uint32_t i=0;i<count;++i)if(indegree[i]==0)zero.push_back(i);std::sort(zero.begin(),zero.end());std::vector<std::uint32_t> order;while(!zero.empty()){auto cur=zero.front();zero.erase(zero.begin());order.push_back(cur);if(h.receiver[cur]&&--indegree[*h.receiver[cur]]==0)zero.insert(std::upper_bound(zero.begin(),zero.end(),*h.receiver[cur]),*h.receiver[cur]);}std::vector<double> capacity(count,-1);for(const auto& c:h.channels)capacity[c.from_index]=c.capacity_volume_m3;double retained=0,overbank=0,exported=0;for(auto i:order){double vol=runoff[i]+incoming[i];if(vol<=0)continue;if(t.samples[i].surface_water!=SurfaceWaterClass::none){retained+=vol;continue;}if(capacity[i]>=0){double r=std::min(vol,capacity[i]);retained+=r;double ov=std::max(0.0,vol-r);if(ov){overbank+=ov;depth[i]=ov/area;}continue;}if(h.receiver[i])incoming[*h.receiver[i]]+=vol;else exported+=vol;}double balance=rain-(infiltration+retained+overbank+exported);return FloodResult{e.id,depth,rain,infiltration,retained,overbank,exported,balance};
}
}
