import test from 'node:test';
import assert from 'node:assert/strict';
import { BusinessLifecycleSystem, type FirmCycleFinancials } from '../src/simulation/economy/BusinessLifecycleSystem.ts';
import type { Firm } from '../src/simulation/economy/FirmSystem.ts';
function firm(p:Partial<Firm>={}):Firm{return{id:'firm:1',buildingId:'b1',zone:'industrial',archetype:'light_manufacturing',status:'operating',jobCapacity:14,filledJobs:10,vacancies:4,productivity:1,cashHealth:0.7,consecutiveLossCycles:0,consecutiveRecoveryCycles:0,formationTick:0,lastOperatingMargin:0,...p};}
const severe=():FirmCycleFinancials=>({revenue:0,inputCost:10,wageCost:10,utilityCost:5,taxCost:5,logisticsCost:20,shortagePenalty:10,operatingMargin:-60});

test('one bad lifecycle cycle cannot close an operating firm',()=>{const update=new BusinessLifecycleSystem().evaluateFirm(firm(),severe(),100);assert.notEqual(update.status,'closed');});
test('same sustained-loss sequence closes on same later tick',()=>{const run=()=>{const sys=new BusinessLifecycleSystem();let f=firm({cashHealth:0.2});let closed=-1;for(const tick of [100,200,300,400,500]){f={...f,...sys.evaluateFirm(f,severe(),tick)};if(f.status==='closed'&&closed<0)closed=tick;}return closed;};assert.equal(run(),run());assert.ok(run()>=400);});
test('distressed firm requires sustained recovery',()=>{const sys=new BusinessLifecycleSystem();let f=firm({status:'distressed',cashHealth:0.5,consecutiveLossCycles:2});const good:FirmCycleFinancials={revenue:100,inputCost:5,wageCost:5,utilityCost:2,taxCost:2,logisticsCost:1,shortagePenalty:0,operatingMargin:85};f={...f,...sys.evaluateFirm(f,good,100)};assert.equal(f.status,'distressed');f={...f,...sys.evaluateFirm(f,good,200)};assert.equal(f.status,'operating');});
test('higher logistics cost reduces operating margin and cash health',()=>{const sys=new BusinessLifecycleSystem();const base=firm();const low=sys.evaluateFirm(base,{revenue:60,inputCost:10,wageCost:10,utilityCost:5,taxCost:5,logisticsCost:2,shortagePenalty:0,operatingMargin:28},100);const high=sys.evaluateFirm(base,{revenue:60,inputCost:10,wageCost:10,utilityCost:5,taxCost:5,logisticsCost:30,shortagePenalty:0,operatingMargin:0},100);assert.ok(low.cashHealth>high.cashHealth);});
test('formation score requires reachable freight access',()=>{const sys=new BusinessLifecycleSystem();const good=sys.scoreFormation({reachableGateway:true,utilityRatio:1,laborAvailability:1,accessibility:1,localDemand:1,sectorGap:1,taxRate:0.1});const bad=sys.scoreFormation({reachableGateway:false,utilityRatio:1,laborAvailability:1,accessibility:1,localDemand:1,sectorGap:1,taxRate:0.1});assert.ok(good>bad);assert.equal(bad,0);});
