import test from 'node:test';
import assert from 'node:assert/strict';
import { TerrainGrid, type TerrainCell } from '../src/world/terrain/TerrainGrid.ts';
import { TreasurySystem } from '../src/simulation/treasury/TreasurySystem.ts';
import { RoadSystem } from '../src/world/roads/RoadSystem.ts';
import { TransportationGraph } from '../src/simulation/traffic/TransportationGraph.ts';
import { PathfindingSystem } from '../src/simulation/traffic/PathfindingSystem.ts';
import { IntersectionSystem } from '../src/simulation/traffic/IntersectionSystem.ts';
import { ServiceFacilitySystem } from '../src/simulation/services/ServiceFacilitySystem.ts';
import { ServiceDispatchSystem } from '../src/simulation/services/ServiceDispatchSystem.ts';
import { ServiceVehicleSystem } from '../src/simulation/services/ServiceVehicleSystem.ts';
import type { Building } from '../src/simulation/buildings/BuildingSystem.ts';

function flatTerrain(width = 24, height = 14): TerrainGrid { const cells: TerrainCell[] = Array.from({ length: width * height }, () => ({ elevation: 0.5, water: false, buildable: true, biome: 'grass' as const })); return new TerrainGrid(width, height, cells); }
function building(id: string, x: number, y: number): Building { return { id, lotId: `lot:${id}`, x, y, zone: 'residential', definitionId: 'residential_fixture', status: 'occupied', constructionStartedTick: 0, completionTick: 0 }; }
function serviceFixture() { const terrain = flatTerrain(); const treasury = new TreasurySystem(500_000); const roads = new RoadSystem(terrain); roads.placePath(Array.from({ length: 16 }, (_, i) => ({ x: i + 2, y: 7 })), 'collector', treasury); const graph = new TransportationGraph(); graph.rebuildIfNeeded(roads); const facilities = new ServiceFacilitySystem(terrain, roads); facilities.restore([{ id: 'service:1', type: 'fire_station', department: 'fire', x: 3, y: 6 }], {}, 2); const vehicles = new ServiceVehicleSystem(); vehicles.syncFleet(facilities); return { terrain, treasury, roads, graph, facilities, vehicles, dispatch: new ServiceDispatchSystem(), pathfinding: new PathfindingSystem(), intersections: new IntersectionSystem() }; }

test('service job follows waiting -> responding -> servicing -> returning -> completed with an explicit routed vehicle', () => { const f = serviceFixture(); const target = building('home', 14, 6); const jobId = f.dispatch.createJob('fire_response', target.id, 0, 0.8); f.dispatch.assignWaiting([target], f.facilities, f.vehicles, f.graph, f.pathfinding, (edge) => edge.freeFlowTicks, 1); assert.equal(f.dispatch.getJob(jobId)?.status, 'responding'); assert.ok(f.dispatch.getJob(jobId)?.assignedVehicleId); const seen = new Set<string>(); for (let tick = 2; tick < 400 && f.dispatch.getJob(jobId)?.status !== 'completed'; tick++) { const events = f.vehicles.step(f.graph, f.intersections, f.pathfinding, (edge) => edge.freeFlowTicks, tick); f.dispatch.applyVehicleEvents(events, tick); const status = f.dispatch.getJob(jobId)?.status; if (status) seen.add(status); } assert.ok(seen.has('servicing')); assert.ok(seen.has('returning')); assert.equal(f.dispatch.getJob(jobId)?.status, 'completed'); assert.equal(f.vehicles.listVehicles()[0]?.state, 'idle'); });

test('dispatch selects the eligible facility with the lowest predicted response cost and an available vehicle', () => { const f = serviceFixture(); f.facilities.restore([{ id: 'service:1', type: 'fire_station', department: 'fire', x: 3, y: 6 }, { id: 'service:2', type: 'fire_station', department: 'fire', x: 13, y: 6 }], {}, 3); f.vehicles.syncFleet(f.facilities); const target = building('home', 16, 6); const jobId = f.dispatch.createJob('fire_response', target.id, 0, 1); f.dispatch.assignWaiting([target], f.facilities, f.vehicles, f.graph, f.pathfinding, (edge) => edge.freeFlowTicks, 1); assert.equal(f.dispatch.getJob(jobId)?.assignedFacilityId, 'service:2'); });

test('unreachable service job stays waiting and never teleports', () => { const f = serviceFixture(); const target = building('isolated', 22, 2); const jobId = f.dispatch.createJob('fire_response', target.id, 0, 1); f.dispatch.assignWaiting([target], f.facilities, f.vehicles, f.graph, f.pathfinding, (edge) => edge.freeFlowTicks, 1); const job = f.dispatch.getJob(jobId)!; assert.equal(job.status, 'waiting'); assert.equal(job.assignedVehicleId, undefined); });

test('intersection service releases emergency vehicles before older normal traffic while normal jobs remain FIFO', () => { const f = serviceFixture(); f.roads.placePath([{ x: 8, y: 5 }, { x: 8, y: 6 }, { x: 8, y: 7 }, { x: 8, y: 8 }], 'local', f.treasury); f.graph.rebuildIfNeeded(f.roads); const node = f.graph.findNodeAt(8, 7)!; const incoming = f.graph.outgoingEdges(node.id)[0]!; f.intersections.enqueue(node.id, incoming.id, { vehicleId: 'normal-old', travelerWeight: 10, queuedTick: 1, priority: 'normal' }); f.intersections.enqueue(node.id, incoming.id, { vehicleId: 'emergency-new', travelerWeight: 1, queuedTick: 2, priority: 'emergency' }); const released = f.intersections.stepNode(f.graph, node.id); assert.deepEqual(released, ['emergency-new']); f.intersections.removeVehicle('normal-old'); f.intersections.enqueue(node.id, incoming.id, { vehicleId: 'garbage-old', travelerWeight: 1, queuedTick: 3, priority: 'normal' }); f.intersections.enqueue(node.id, incoming.id, { vehicleId: 'commuter-new', travelerWeight: 1, queuedTick: 4, priority: 'normal' }); assert.deepEqual(f.intersections.stepNode(f.graph, node.id).slice(0, 2), ['garbage-old', 'commuter-new']); });

test('road demolition reroutes or fails a service vehicle without leaving a stale queue entry', () => { const f = serviceFixture(); const target = building('home', 14, 6); const jobId = f.dispatch.createJob('fire_response', target.id, 0, 1); f.dispatch.assignWaiting([target], f.facilities, f.vehicles, f.graph, f.pathfinding, (edge) => edge.freeFlowTicks, 1); assert.equal(f.dispatch.getJob(jobId)?.status, 'responding'); f.roads.remove(8, 7); f.graph.rebuildIfNeeded(f.roads); const events = f.vehicles.step(f.graph, f.intersections, f.pathfinding, (edge) => edge.freeFlowTicks, 2); f.dispatch.applyVehicleEvents(events, 2); assert.equal(f.dispatch.getJob(jobId)?.status, 'waiting'); assert.equal(f.intersections.queueLength(), 0); assert.equal(f.vehicles.listVehicles()[0]?.state, 'idle'); });
