import test from 'node:test'; import assert from 'node:assert/strict';
import { TerrainGrid } from '../src/world/terrain/TerrainGrid.ts'; import { RoadSystem } from '../src/world/roads/RoadSystem.ts'; import { TreasurySystem } from '../src/simulation/treasury/TreasurySystem.ts'; import { TransportationGraph } from '../src/simulation/traffic/TransportationGraph.ts'; import { PathfindingSystem } from '../src/simulation/traffic/PathfindingSystem.ts'; import { TransitNetworkSystem } from '../src/simulation/transit/TransitNetworkSystem.ts'; import { MobilityScheduler,type MobilityPersonTrip } from '../src/simulation/mobility/MobilityScheduler.ts'; import { DemandSystem } from '../src/simulation/demand/DemandSystem.ts'; import { EconomySystem } from '../src/simulation/economy/EconomySystem.ts';
function scenario(headway=20,fare=0,mode:'bus'|'brt'|'tram'|'metro'='bus'){const terrain=TerrainGrid.generate(16,5,2),roads=new RoadSystem(terrain),treasury=new TreasurySystem(1e6);roads.placePath(Array.from({length:14},(_,i)=>({x:i+1,y:2})),'local',treasury);const graph=new TransportationGraph();graph.rebuildIfNeeded(roads);const transit=new TransitNetworkSystem(terrain,roads);const stopType=mode==='metro'?'metro_station':'surface_stop';const a=transit.placeStop(stopType,2,1,treasury).id!,b=transit.placeStop(stopType,13,1,treasury).id!;const line=transit.createLine(mode);transit.setLineStops(line,[a,b]);transit.setHeadway(line,headway);transit.setFare(line,fare);transit.setEnabled(line,true);return{graph,transit,line,path:new PathfindingSystem()};}
const trip:MobilityPersonTrip={id:'p1',sourceTripId:'t1',originBuildingId:'a',destinationBuildingId:'b',originRoadNodeId:'n:2,2',destinationRoadNodeId:'n:13,2',departureTick:100,travelerWeight:20,purpose:'commute'};
test('competitive transit diverts weighted trips from cars and improves person accessibility',()=>{const s=scenario(20,0,'brt'),m=new MobilityScheduler();let car=0;for(let t=0;t<=100;t++)m.tick({tick:t,roadGraph:s.graph,transit:s.transit,pathfinding:s.path,roadTravelTime:e=>e.freeFlowTicks*4,generateTrips:()=>t===100?[trip]:[],submitCarTrip:(_,w)=>{car+=w;}});const x=m.snapshot();assert.equal(car,0);assert.equal(x.transitModeShare,1);assert.equal(x.modeShares.brt,1);assert.equal(x.modeShares.car,0);assert.ok(x.personAccessibility>0.2);});
test('poor high-wait expensive transit does not magically beat car travel',()=>{const s=scenario(600,20),m=new MobilityScheduler();let car=0;for(let t=0;t<=100;t++)m.tick({tick:t,roadGraph:s.graph,transit:s.transit,pathfinding:s.path,roadTravelTime:e=>e.freeFlowTicks,generateTrips:()=>t===100?[trip]:[],submitCarTrip:(_,w)=>{car+=w;}});assert.equal(car,20);const snapshot=m.snapshot();assert.equal(snapshot.carModeShare,1);assert.equal(snapshot.modeShares.car,1);});
test('crowding penalty can return marginal travelers to cars',()=>{const s=scenario(60,1),m=new MobilityScheduler();let car=0;m.setCrowdingPenaltyTicks(500);for(let t=0;t<=100;t++)m.tick({tick:t,roadGraph:s.graph,transit:s.transit,pathfinding:s.path,roadTravelTime:e=>e.freeFlowTicks*1.5,generateTrips:()=>t===100?[trip]:[],submitCarTrip:(_,w)=>{car+=w;}});assert.equal(car,20);});
test('person accessibility changes demand only within existing bounded accessibility channel',()=>{const d=new DemandSystem();const base={population:100,housingCapacity:90,workforce:50,employed:45,totalJobs:60,powerRatio:1,waterRatio:1,garbageRatio:1,taxRates:{residential:.1,commercial:.1,industrial:.1},trafficJobAccessibility:.2,trafficCommercialAccessibility:.2,serviceQuality:.7,commercialServiceQuality:.7};const low=d.evaluate({...base,personAccessibility:.2}),high=d.evaluate({...base,personAccessibility:.9});assert.ok(high.residential>low.residential);assert.ok(high.residential-low.residential<=0.2);});
test('transit fares and operating costs settle explicitly in municipal economy',()=>{const e=new EconomySystem();const treasury=new TreasurySystem(1000);const r=e.settle(treasury,{residential:0,commercial:0,industrial:0,total:100},0,0,80,30);assert.equal(r.transitOperatingCost,80);assert.equal(r.transitFareRevenue,30);assert.equal(r.netRecurringBalance,50);assert.equal(treasury.balance,1050);});
test('mobility fiscal settlement consumes only new transit activity',()=>{const s=scenario(20,0,'brt'),m=new MobilityScheduler();for(let t=0;t<40;t++)m.tick({tick:t,roadGraph:s.graph,transit:s.transit,pathfinding:s.path,roadTravelTime:e=>e.freeFlowTicks,generateTrips:()=>[],submitCarTrip:()=>{}});const first=m.consumeFiscalDelta();const second=m.consumeFiscalDelta();assert.ok(first.operatingCost>0);assert.equal(second.operatingCost,0);assert.equal(second.fareRevenue,0);});
