import test from 'node:test';
import assert from 'node:assert/strict';
import { PassengerQueueSystem, type TransitPassengerCohort } from '../src/simulation/transit/PassengerQueueSystem.ts';
function cohort(id: string, weight: number, overrides: Partial<TransitPassengerCohort> = {}): TransitPassengerCohort { return { id, personTripId: `person:${id}`, travelerWeight: weight, lineId: 'line:1', directionKey: 'outbound', boardingStopId: 'stop:a', alightingStopId: 'stop:b', destinationRoadNodeId: 'n:9,9', enqueuedTick: 10, transferLegs: [], ...overrides }; }
test('boarding is deterministic FIFO by enqueue tick then cohort ID', () => { const q=new PassengerQueueSystem(); q.enqueue('stop:a','line:1','outbound',cohort('b',3,{enqueuedTick:10})); q.enqueue('stop:a','line:1','outbound',cohort('a',2,{enqueuedTick:10})); const r=q.board('stop:a','line:1','outbound',5); assert.deepEqual(r.boarded.map(i=>i.personTripId),['person:a','person:b']); assert.equal(r.boardedWeight,5); assert.equal(r.leftBehindWeight,0); });
test('partial boarding splits weighted cohorts without losing passengers', () => { const q=new PassengerQueueSystem(); q.enqueue('stop:a','line:1','outbound',cohort('large',10)); const r=q.board('stop:a','line:1','outbound',6); assert.equal(r.boardedWeight,6); assert.equal(r.boarded[0]?.travelerWeight,6); assert.match(r.boarded[0]?.id??'',/^passenger-split:/); assert.equal(q.waitingWeight('stop:a','line:1','outbound'),4); assert.equal(r.leftBehindWeight,4); });
test('capacity leaves later FIFO cohorts waiting', () => { const q=new PassengerQueueSystem(); q.enqueue('stop:a','line:1','outbound',cohort('first',4)); q.enqueue('stop:a','line:1','outbound',cohort('second',4,{enqueuedTick:11})); const r=q.board('stop:a','line:1','outbound',4); assert.deepEqual(r.boarded.map(i=>i.personTripId),['person:first']); assert.equal(r.leftBehindWeight,4); assert.deepEqual(q.peek('stop:a','line:1','outbound').map(i=>i.personTripId),['person:second']); });
test('alighting transfer cohorts can be enqueued onto their next line', () => { const q=new PassengerQueueSystem(); const x=cohort('x',5,{alightingStopId:'stop:mid',transferLegs:[{lineId:'line:2',directionKey:'outbound',boardingStopId:'stop:mid',alightingStopId:'stop:end'}]}); const {alighted,continuing}=q.alight([x],'stop:mid'); assert.equal(continuing.length,0); assert.equal(alighted.length,1); assert.equal(q.enqueueNextTransfer(alighted[0]!,30),true); assert.equal(q.waitingWeight('stop:mid','line:2','outbound'),5); assert.equal(q.peek('stop:mid','line:2','outbound')[0]?.alightingStopId,'stop:end'); });
test('snapshot restore preserves queue ordering and deterministic split IDs', () => { const q=new PassengerQueueSystem(); q.enqueue('stop:a','line:1','outbound',cohort('a',8)); q.board('stop:a','line:1','outbound',3); const s=q.snapshot(); const restored=new PassengerQueueSystem(); restored.restore(s); assert.deepEqual(restored.snapshot(),s); assert.equal(restored.board('stop:a','line:1','outbound',2).boarded[0]?.id,'passenger-split:2'); });
test('invalidating a stop or line removes affected riders and returns them for replanning', () => { const q=new PassengerQueueSystem(); q.enqueue('stop:a','line:1','outbound',cohort('a',3)); q.enqueue('stop:c','line:2','outbound',cohort('b',4,{lineId:'line:2',boardingStopId:'stop:c'})); assert.equal(q.invalidateStop('stop:a').reduce((s,i)=>s+i.travelerWeight,0),3); assert.equal(q.invalidateLine('line:2').reduce((s,i)=>s+i.travelerWeight,0),4); assert.equal(q.totalWaitingWeight(),0); });
