option(CIVIC_ENABLE_SANITIZERS "Enable supported native sanitizers" OFF)
option(CIVIC_BUILD_TESTS "Build civic_engine tests" ON)
option(CIVIC_BUILD_NAPI "Build the Node-API binding" OFF)
option(CIVIC_BUILD_WASM "Build the WebAssembly bridge" OFF)
if(WIN32)
  option(CIVIC_BUILD_NATIVE_CLIENT "Build the native Windows presentation client" ON)
else()
  option(CIVIC_BUILD_NATIVE_CLIENT "Build the native Windows presentation client" OFF)
endif()
