#pragma once

#include <algorithm>
#include <cmath>
#include <compare>
#include <cstdint>
#include <limits>
#include <map>
#include <optional>
#include <set>
#include <string>
#include <string_view>
#include <tuple>
#include <utility>
#include <vector>

#include <civic/core/Error.hpp>

namespace civic::transport {

template<class Tag> class StableId final {
public:
    StableId() = default;
    explicit StableId(std::string_view value) : value_(value) {}
    [[nodiscard]] const std::string& value() const noexcept { return value_; }
    [[nodiscard]] bool empty() const noexcept { return value_.empty(); }
    auto operator<=>(const StableId&) const = default;
private: std::string value_;
};
struct SegmentIdTag; struct CarriagewayIdTag; struct LaneIdTag; struct LaneGroupIdTag; struct JunctionIdTag; struct MovementIdTag;
struct SignalPlanIdTag; struct ParkingFacilityIdTag; struct IncidentIdTag; struct RouteIdTag; struct TripIdTag; struct TransitStopIdTag;
struct TransitLineIdTag; struct TransitRunIdTag; struct PassengerCohortIdTag; struct TransitVehicleIdTag;
using SegmentId=StableId<SegmentIdTag>; using CarriagewayId=StableId<CarriagewayIdTag>; using LaneId=StableId<LaneIdTag>;
using LaneGroupId=StableId<LaneGroupIdTag>; using JunctionId=StableId<JunctionIdTag>; using MovementId=StableId<MovementIdTag>;
using SignalPlanId=StableId<SignalPlanIdTag>; using ParkingFacilityId=StableId<ParkingFacilityIdTag>; using IncidentId=StableId<IncidentIdTag>;
using RouteId=StableId<RouteIdTag>; using TripId=StableId<TripIdTag>; using TransitStopId=StableId<TransitStopIdTag>;
using TransitLineId=StableId<TransitLineIdTag>; using TransitRunId=StableId<TransitRunIdTag>; using PassengerCohortId=StableId<PassengerCohortIdTag>;
using TransitVehicleId=StableId<TransitVehicleIdTag>;

enum class RoadClass:std::uint8_t{local,collector,arterial,avenue,expressway,highway}; enum class Direction:std::uint8_t{forward,backward};
enum class LaneType:std::uint8_t{through,turn,bus,bike,parking,reversible,shoulder}; enum class LaneState:std::uint8_t{open,closed};
enum class MovementType:std::uint8_t{left,through,right,u_turn}; enum class ControlType:std::uint8_t{uncontrolled,stop,yield,signalized};
enum class IncidentState:std::uint8_t{scheduled,active,cleared}; enum class ParkingKind:std::uint8_t{curb,private_lot,lot,garage};
enum class TripCause:std::uint8_t{home_work,home_school,home_shopping,firm_supplier,warehouse_customer,incident_facility,construction_supplier};
enum class TravelMode:std::uint8_t{car,transit,walk,bicycle,unmet}; enum class TransitMode:std::uint8_t{bus,brt,tram,metro};
enum class TransitVehicleState:std::uint8_t{in_service,dwelling,out_of_service,failed};
using VehiclePermissionMask=std::uint32_t;
inline constexpr VehiclePermissionMask permission_private_car=1U<<0U, permission_taxi=1U<<1U, permission_light_commercial=1U<<2U,
 permission_heavy_freight=1U<<3U, permission_bus=1U<<4U, permission_emergency=1U<<5U, permission_bicycle=1U<<6U,
 all_vehicle_permissions=(1U<<7U)-1U;
[[nodiscard]] constexpr bool permissionCompatible(VehiclePermissionMask available,VehiclePermissionMask requested) noexcept{return requested!=0U&&(available&requested)==requested;}

struct RoadClassDefinition final{std::uint32_t legacyLaneCount{};double capacityPerMinute{};double freeFlowSpeedCellsPerSecond{};double freeFlowSpeedKph{};};
[[nodiscard]] const RoadClassDefinition& roadClassDefinition(RoadClass); [[nodiscard]] Result<RoadClass> parseRoadClass(std::string_view); [[nodiscard]] std::string_view toString(RoadClass) noexcept;
struct Junction final{JunctionId id;double x{},y{};std::optional<std::string> sourceLegacyCell;auto operator<=>(const Junction&)const=default;};
struct RoadSegment final{SegmentId id;RoadClass roadClass{RoadClass::local};std::string geometryRef;JunctionId startJunctionId,endJunctionId;double lengthMeters{1},speedLimitKph{},condition{1};std::string accessPolicyId{"default"};std::optional<std::string> tollPolicyId;std::vector<CarriagewayId> carriagewayIds;std::vector<std::string> sourceLegacyCells;auto operator<=>(const RoadSegment&)const=default;};
struct Carriageway final{CarriagewayId id;SegmentId segmentId;Direction direction{Direction::forward};JunctionId fromJunctionId,toJunctionId;RoadClass operatingClass{RoadClass::local};std::vector<LaneId> laneIds;auto operator<=>(const Carriageway&)const=default;};
struct Lane final{LaneId id;CarriagewayId carriagewayId;std::uint32_t ordinal{};LaneType type{LaneType::through};VehiclePermissionMask permissions{all_vehicle_permissions};LaneState operatingState{LaneState::open};double baseCapacityPerMinute{},freeFlowSpeedKph{};auto operator<=>(const Lane&)const=default;};
struct TurnMovement final{MovementId id;JunctionId junctionId;CarriagewayId fromCarriagewayId,toCarriagewayId;std::vector<LaneId> fromLaneIds,toLaneIds;MovementType type{MovementType::through};VehiclePermissionMask permissions{all_vehicle_permissions};bool allowed{true};double basePenaltyTicks{};auto operator<=>(const TurnMovement&)const=default;};
struct TransportAuthority{std::vector<Junction> junctions;std::vector<RoadSegment> segments;std::vector<Carriageway> carriageways;std::vector<Lane> lanes;std::vector<TurnMovement> movements;auto operator<=>(const TransportAuthority&)const=default;};
struct TransportNetworkSnapshot final:TransportAuthority{std::uint64_t topologyRevision{},costRevision{};auto operator<=>(const TransportNetworkSnapshot&)const=default;};
struct MutationResult final{bool ok{},changed{};std::string reason;};
class TransportNetworkStore final{public:[[nodiscard]]MutationResult replaceAuthority(TransportAuthority);[[nodiscard]]MutationResult setLaneOperatingState(const LaneId&,LaneState);[[nodiscard]]MutationResult setLanePermissions(const LaneId&,VehiclePermissionMask);[[nodiscard]]MutationResult setMovementAllowed(const MovementId&,bool);[[nodiscard]]MutationResult setMovementPermissions(const MovementId&,VehiclePermissionMask);[[nodiscard]]std::uint64_t advanceCostRevision()noexcept{return++cost_revision_;}[[nodiscard]]TransportNetworkSnapshot snapshot()const;[[nodiscard]]Result<void> restore(const TransportNetworkSnapshot&);[[nodiscard]]Result<void> validate()const;[[nodiscard]]Result<void> validate(const TransportAuthority&)const;[[nodiscard]]const Carriageway* carriageway(const CarriagewayId&)const noexcept;[[nodiscard]]const Lane* lane(const LaneId&)const noexcept;[[nodiscard]]const TurnMovement* movement(const MovementId&)const noexcept;[[nodiscard]]std::uint64_t topologyRevision()const noexcept{return topology_revision_;}[[nodiscard]]std::uint64_t costRevision()const noexcept{return cost_revision_;}private:TransportAuthority authority_;std::uint64_t topology_revision_{},cost_revision_{};};
struct LaneGroup final{LaneGroupId id;CarriagewayId carriagewayId;std::vector<LaneId> laneIds;std::vector<MovementId> movementIds;VehiclePermissionMask permissions{};double capacityPerMinute{},freeFlowSpeedKph{};auto operator<=>(const LaneGroup&)const=default;};
[[nodiscard]]Result<std::vector<LaneGroup>> buildLaneGroups(const TransportNetworkSnapshot&);
struct LegacyRoadCell final{std::int32_t x{},y{};RoadClass roadClass{RoadClass::local};auto operator<=>(const LegacyRoadCell&)const=default;};struct LegacyRoadState final{std::uint64_t revision{};std::vector<LegacyRoadCell> cells;};struct MigrationDiagnostic final{std::string code,message;};struct LegacyMigrationResult final{TransportAuthority authority;std::vector<MigrationDiagnostic> diagnostics;};class LegacyRoadMigrationAdapter final{public:[[nodiscard]]Result<LegacyMigrationResult> project(const LegacyRoadState&)const;};
struct MovementConflict final{MovementId first,second;bool conflicts{};auto operator<=>(const MovementConflict&)const=default;};struct ConflictMatrix final{JunctionId junctionId;std::vector<MovementConflict> entries;[[nodiscard]]bool conflicts(const MovementId&,const MovementId&)const noexcept;};[[nodiscard]]Result<ConflictMatrix> buildConflictMatrix(const TransportNetworkSnapshot&,const JunctionId&);
struct SignalPhase final{std::string id;std::vector<MovementId> greenMovements;std::uint64_t durationTicks{1};auto operator<=>(const SignalPhase&)const=default;};struct SignalPlan final{SignalPlanId id;JunctionId junctionId;std::vector<SignalPhase> phases;std::uint64_t offsetTicks{};auto operator<=>(const SignalPlan&)const=default;};struct IntersectionControl final{JunctionId junctionId;ControlType type{ControlType::uncontrolled};std::optional<SignalPlanId> signalPlanId;double stopDelayTicks{},yieldDelayTicks{};auto operator<=>(const IntersectionControl&)const=default;};
class IntersectionControlSystem final{public:[[nodiscard]]Result<void> restore(std::vector<IntersectionControl>,std::vector<SignalPlan>,const TransportNetworkSnapshot&);[[nodiscard]]Result<void> setControl(IntersectionControl,const TransportNetworkSnapshot&);[[nodiscard]]Result<void> setSignalPlan(SignalPlan,const TransportNetworkSnapshot&);[[nodiscard]]bool movementGreen(const MovementId&,const JunctionId&,std::uint64_t)const noexcept;[[nodiscard]]double delayTicks(const TurnMovement&,std::uint64_t)const noexcept;[[nodiscard]]std::uint64_t revision()const noexcept{return revision_;}[[nodiscard]]const std::map<JunctionId,IntersectionControl>& controls()const noexcept{return controls_;}[[nodiscard]]const std::map<SignalPlanId,SignalPlan>& signalPlans()const noexcept{return signal_plans_;}private:std::map<JunctionId,IntersectionControl> controls_;std::map<SignalPlanId,SignalPlan> signal_plans_;std::uint64_t revision_{};};
struct ParkingFacility final{ParkingFacilityId id;ParkingKind kind{ParkingKind::lot};JunctionId accessJunctionId;double capacity{},occupied{},price{},accessPenaltyTicks{};auto operator<=>(const ParkingFacility&)const=default;};class ParkingSystem final{public:[[nodiscard]]Result<void> restore(std::vector<ParkingFacility>,const TransportNetworkSnapshot&);[[nodiscard]]Result<void> upsert(ParkingFacility,const TransportNetworkSnapshot&);[[nodiscard]]Result<void> reserve(const ParkingFacilityId&,double);[[nodiscard]]Result<void> release(const ParkingFacilityId&,double);[[nodiscard]]double generalizedCost(const JunctionId&)const noexcept;[[nodiscard]]std::uint64_t revision()const noexcept{return revision_;}[[nodiscard]]std::vector<ParkingFacility> snapshot()const;private:std::map<ParkingFacilityId,ParkingFacility> facilities_;std::uint64_t revision_{};};
struct Incident final{IncidentId id;std::vector<CarriagewayId> carriagewayIds;std::vector<LaneId> laneIds;std::vector<MovementId> movementIds;std::uint64_t startTick{},clearTick{};double capacityFactor{1},speedFactor{1},fixedPenaltyTicks{};IncidentState state{IncidentState::scheduled};auto operator<=>(const Incident&)const=default;};class IncidentSystem final{public:[[nodiscard]]Result<void> restore(std::vector<Incident>,const TransportNetworkSnapshot&,std::uint64_t);[[nodiscard]]Result<void> upsert(Incident,const TransportNetworkSnapshot&,std::uint64_t);[[nodiscard]]bool step(std::uint64_t)noexcept;[[nodiscard]]double capacityFactor(const CarriagewayId&)const noexcept;[[nodiscard]]double speedFactor(const CarriagewayId&)const noexcept;[[nodiscard]]double penaltyTicks(const CarriagewayId&)const noexcept;[[nodiscard]]bool movementBlocked(const MovementId&)const noexcept;[[nodiscard]]std::uint64_t revision()const noexcept{return revision_;}[[nodiscard]]std::vector<Incident> snapshot()const;private:std::map<IncidentId,Incident> incidents_;std::uint64_t revision_{};};
struct RoutePreference final{double valueOfTime{1},tollWeight{1},parkingWeight{1},incidentWeight{1},reliabilityWeight{};VehiclePermissionMask vehiclePermissions{permission_private_car};};struct RouteRequest final{JunctionId origin,destination;RoutePreference preference;std::uint64_t tick{};};struct RouteResult final{RouteId id;std::vector<CarriagewayId> carriageways;std::vector<MovementId> movements;double generalizedCost{},travelTimeTicks{};bool reachable{};auto operator<=>(const RouteResult&)const=default;};
class MovementAwareRouter final{public:[[nodiscard]]Result<RouteResult> route(const TransportNetworkSnapshot&,const IntersectionControlSystem&,const ParkingSystem&,const IncidentSystem&,const RouteRequest&);void clear()noexcept{cache_.clear();}[[nodiscard]]std::size_t cacheSize()const noexcept{return cache_.size();}private:struct CacheKey final{JunctionId origin,destination;VehiclePermissionMask permissions{};std::uint64_t topologyRevision{},controlRevision{},costRevision{},parkingRevision{},incidentRevision{},preferenceHash{};auto operator<=>(const CacheKey&)const=default;};std::map<CacheKey,RouteResult> cache_;};
struct LaneTrafficState final{LaneGroupId laneGroupId;double vehicleStock{},enteringFlowPerMinute{},capacityPerMinute{},speedKph{};auto operator<=>(const LaneTrafficState&)const=default;};class TrafficFlowState final{public:[[nodiscard]]Result<void> rebuild(const TransportNetworkSnapshot&,const IncidentSystem&);[[nodiscard]]Result<void> restore(const std::vector<LaneTrafficState>&,const TransportNetworkSnapshot&,const IncidentSystem&);[[nodiscard]]Result<void> addStock(const LaneGroupId&,double);[[nodiscard]]Result<void> transfer(const LaneGroupId&,const LaneGroupId&,double);[[nodiscard]]Result<void> recordFlow(const LaneGroupId&,double);[[nodiscard]]double totalStock()const noexcept;[[nodiscard]]std::vector<LaneTrafficState> snapshot()const;private:std::map<LaneGroupId,LaneTrafficState> states_;};
struct TripDemand final{TripId id;TripCause cause{TripCause::home_work};JunctionId origin,destination;double travelerWeight{};auto operator<=>(const TripDemand&)const=default;};struct WeightedDestination final{JunctionId destination;double share{};auto operator<=>(const WeightedDestination&)const=default;};class CausalTripGenerator final{public:[[nodiscard]]Result<std::vector<TripDemand>> generate(TripCause,const JunctionId&,double,std::vector<WeightedDestination>);[[nodiscard]]std::uint64_t nextSequence()const noexcept{return next_sequence_;}void restoreSequence(std::uint64_t value)noexcept{next_sequence_=std::max<std::uint64_t>(1,value);}private:std::uint64_t next_sequence_{1};};
struct ModeAlternative final{TravelMode mode{TravelMode::unmet};double generalizedCost{std::numeric_limits<double>::infinity()};bool available{};};struct ModeChoiceResult final{TravelMode mode{TravelMode::unmet};double generalizedCost{std::numeric_limits<double>::infinity()};};class ModeChoiceSystem final{public:[[nodiscard]]Result<ModeChoiceResult> choose(std::vector<ModeAlternative>)const;};
struct TransitStop final{TransitStopId id;JunctionId roadJunctionId;std::string name;bool accessible{true};auto operator<=>(const TransitStop&)const=default;};struct TransitLine final{TransitLineId id;std::string name;TransitMode mode{TransitMode::bus};std::vector<TransitStopId> stopIds;double fare{};std::uint64_t headwayTicks{60};double reliability{1};bool enabled{true};auto operator<=>(const TransitLine&)const=default;};struct TransitNetworkSnapshot final{std::vector<TransitStop> stops;std::vector<TransitLine> lines;std::uint64_t revision{};};class TransitNetwork final{public:[[nodiscard]]Result<void> restore(const TransitNetworkSnapshot&,const TransportNetworkSnapshot&);[[nodiscard]]Result<void> upsertStop(TransitStop,const TransportNetworkSnapshot&);[[nodiscard]]Result<void> upsertLine(TransitLine);[[nodiscard]]TransitNetworkSnapshot snapshot()const;[[nodiscard]]const TransitStop* stop(const TransitStopId&)const noexcept;[[nodiscard]]const TransitLine* line(const TransitLineId&)const noexcept;[[nodiscard]]std::uint64_t revision()const noexcept{return revision_;}private:std::map<TransitStopId,TransitStop> stops_;std::map<TransitLineId,TransitLine> lines_;std::uint64_t revision_{};};
struct TransitTransferLeg final{TransitLineId lineId;std::string directionKey;TransitStopId boardingStopId,alightingStopId;auto operator<=>(const TransitTransferLeg&)const=default;};struct PassengerCohort final{PassengerCohortId id;TripId personTripId;double travelerWeight{};TransitLineId lineId;std::string directionKey;TransitStopId boardingStopId,alightingStopId;JunctionId destinationRoadJunctionId;std::uint64_t enqueuedTick{};std::vector<TransitTransferLeg> transferLegs;auto operator<=>(const PassengerCohort&)const=default;};struct PassengerQueueEntry final{TransitStopId stopId;TransitLineId lineId;std::string directionKey;std::vector<PassengerCohort> cohorts;auto operator<=>(const PassengerQueueEntry&)const=default;};struct PassengerQueueSnapshot final{std::uint64_t nextSplitId{1};std::vector<PassengerQueueEntry> queues;double generatedWeight{},completedWeight{},cancelledWeight{};};struct BoardingResult final{std::vector<PassengerCohort> boarded;double boardedWeight{},leftBehindWeight{};};
class PassengerQueueSystem final{public:[[nodiscard]]Result<void> restore(const PassengerQueueSnapshot&,const TransitNetwork&);[[nodiscard]]Result<void> enqueue(const PassengerCohort&,const TransitNetwork&);[[nodiscard]]Result<void> requeue(const PassengerCohort&,const TransitNetwork&);[[nodiscard]]BoardingResult board(const TransitStopId&,const TransitLineId&,std::string_view,double);[[nodiscard]]Result<void> enqueueNextTransfer(PassengerCohort,std::uint64_t,const TransitNetwork&);void markCompleted(double w)noexcept{completed_weight_+=std::max(0.0,w);}void markCancelled(double w)noexcept{cancelled_weight_+=std::max(0.0,w);}[[nodiscard]]double waitingWeight()const noexcept;[[nodiscard]]double generatedWeight()const noexcept{return generated_weight_;}[[nodiscard]]double completedWeight()const noexcept{return completed_weight_;}[[nodiscard]]double cancelledWeight()const noexcept{return cancelled_weight_;}[[nodiscard]]PassengerQueueSnapshot snapshot()const;private:[[nodiscard]]Result<void> enqueueInternal(const PassengerCohort&,const TransitNetwork&,bool);[[nodiscard]]static std::string key(const TransitStopId&,const TransitLineId&,std::string_view);std::map<std::string,PassengerQueueEntry> queues_;std::set<PassengerCohortId> known_ids_;std::uint64_t next_split_id_{1};double generated_weight_{},completed_weight_{},cancelled_weight_{};};
struct TransitVehicle final{TransitVehicleId id;TransitRunId runId;TransitLineId lineId;std::string directionKey;std::size_t stopIndex{};double capacity{};TransitVehicleState state{TransitVehicleState::in_service};std::vector<PassengerCohort> onboard;std::uint64_t nextActionTick{};auto operator<=>(const TransitVehicle&)const=default;};struct TransitOperationsSnapshot final{std::vector<TransitVehicle> vehicles;std::uint64_t nextRunId{1},nextVehicleId{1};double completedPassengerWeight{};};class TransitOperations final{public:[[nodiscard]]Result<void> restore(const TransitOperationsSnapshot&,const TransitNetwork&);[[nodiscard]]Result<TransitVehicleId> dispatch(const TransitLineId&,double,std::uint64_t,const TransitNetwork&);[[nodiscard]]Result<void> step(std::uint64_t,const TransitNetwork&,PassengerQueueSystem&);[[nodiscard]]Result<void> failVehicle(const TransitVehicleId&,std::uint64_t,const TransitNetwork&,PassengerQueueSystem&);[[nodiscard]]double onboardWeight()const noexcept;[[nodiscard]]double activeCapacity()const noexcept;[[nodiscard]]double crowdingRatio()const noexcept;[[nodiscard]]double completedPassengerWeight()const noexcept{return completed_passenger_weight_;}[[nodiscard]]TransitOperationsSnapshot snapshot()const;private:std::map<TransitVehicleId,TransitVehicle> vehicles_;std::uint64_t next_run_id_{1},next_vehicle_id_{1};double completed_passenger_weight_{};};
struct JourneyLeg final{TravelMode mode{TravelMode::unmet};JunctionId from,to;std::optional<TransitLineId> lineId;std::optional<TransitStopId> boardStopId,alightStopId;double generalizedCost{};auto operator<=>(const JourneyLeg&)const=default;};struct JourneyPlan final{std::vector<JourneyLeg> legs;double totalGeneralizedCost{};bool reachable{};};class MultimodalJourneyPlanner final{public:[[nodiscard]]Result<JourneyPlan> plan(const JunctionId&,const JunctionId&,const TransportNetworkSnapshot&,const TransitNetwork&,MovementAwareRouter&,const IntersectionControlSystem&,const ParkingSystem&,const IncidentSystem&,std::uint64_t);};
struct TransportationSnapshot final{TransportNetworkSnapshot network;std::vector<LaneGroup> laneGroups;std::vector<IntersectionControl> controls;std::vector<SignalPlan> signalPlans;std::vector<ParkingFacility> parking;std::vector<Incident> incidents;std::vector<LaneTrafficState> traffic;TransitNetworkSnapshot transitNetwork;PassengerQueueSnapshot passengerQueues;TransitOperationsSnapshot transitOperations;std::uint64_t revision{};};
class TransportationEngine final{public:[[nodiscard]]Result<void> migrateLegacyRoads(const LegacyRoadState&);[[nodiscard]]Result<void> restoreNetwork(const TransportNetworkSnapshot&);[[nodiscard]]Result<void> restoreTransit(const TransitNetworkSnapshot&,const PassengerQueueSnapshot&,const TransitOperationsSnapshot&);[[nodiscard]]Result<void> restoreSnapshot(const TransportationSnapshot&,std::uint64_t);[[nodiscard]]Result<void> step(std::uint64_t);[[nodiscard]]Result<void> applyCommand(std::string_view,std::string_view,std::uint64_t);[[nodiscard]]Result<RouteResult> route(const RouteRequest&);[[nodiscard]]Result<TransportationSnapshot> snapshot()const;[[nodiscard]]Result<void> validate()const;[[nodiscard]]TransportNetworkStore& network()noexcept{return network_;}[[nodiscard]]const TransportNetworkStore& network()const noexcept{return network_;}[[nodiscard]]IntersectionControlSystem& controls()noexcept{return controls_;}[[nodiscard]]ParkingSystem& parking()noexcept{return parking_;}[[nodiscard]]IncidentSystem& incidents()noexcept{return incidents_;}[[nodiscard]]TrafficFlowState& traffic()noexcept{return traffic_;}[[nodiscard]]CausalTripGenerator& trips()noexcept{return trips_;}[[nodiscard]]ModeChoiceSystem& modeChoice()noexcept{return mode_choice_;}[[nodiscard]]TransitNetwork& transitNetwork()noexcept{return transit_network_;}[[nodiscard]]PassengerQueueSystem& passengerQueues()noexcept{return passenger_queues_;}[[nodiscard]]TransitOperations& transitOperations()noexcept{return transit_operations_;}[[nodiscard]]MovementAwareRouter& router()noexcept{return router_;}[[nodiscard]]std::uint64_t revision()const noexcept{return revision_;}private:void bumpCostRevision();TransportNetworkStore network_;IntersectionControlSystem controls_;ParkingSystem parking_;IncidentSystem incidents_;MovementAwareRouter router_;TrafficFlowState traffic_;CausalTripGenerator trips_;ModeChoiceSystem mode_choice_;TransitNetwork transit_network_;PassengerQueueSystem passenger_queues_;TransitOperations transit_operations_;std::uint64_t revision_{};};
[[nodiscard]]std::uint64_t canonicalHash(const TransportationSnapshot&)noexcept;

} // namespace civic::transport
